package io.github.thisismeamir.kortex.core.objs.getmodel

import kotlinx.serialization.Serializable

@Serializable
data class Model(
    val aiTemplate: String,
    val created: Double,
    val ctxLen: Int,
    val dynatempExponent: Double,
    val dynatempRange: Double,
    val engine: String,
    val files: List<String>,
    val frequencyPenalty: Double,
    val gpuArch: String,
    val id: String,
    val ignoreEos: Boolean,
    val maxTokens: Int,
    val minKeep: Int,
    val minP: Double,
    val mirostat: Boolean,
    val mirostatEta: Double,
    val mirostatTau: Double,
    val model: String,
    val nParallel: Int,
    val nProbs: Int,
    val name: String,
    val ngl: Int,
    val `object`: String,
    val os: String,
    val ownedBy: String,
    val penalizeNl: Boolean,
    val precision: String,
    val presencePenalty: Double,
    val promptTemplate: String,
    val quantizationMethod: String,
    val repeatLastN: Int,
    val repeatPenalty: Double,
    val seed: Int,
    val size: Double,
    val status: String = "",
    val stream: Boolean,
    val systemTemplate: String,
    val temperature: Double,
    val textModel: Boolean,
    val tfsZ: Double,
    val topK: Int,
    val topP: Double,
    val typP: Double,
    val userTemplate: String,
    val version: String,
    val recommendation: Recommendation? = null,
    val stop: List<String>
)